### DISCUSSION TITLE
Docker Compose Datastore Connection Refused after Max retries exceeded with

### DISCUSSION THREAD

**Discussion by MichaelHarmsTIB** [ckan/ckan#7656] [General]
## Describe the bug
URL error: HTTPConnectionPool(host='localhost', port=80): Max retries exceeded with url: /dataset/ca8a57bc-953d-4e43-99a4-c06454f010b5/resource/7439d92f-420f-4b06-ba94-1de624e0d4fb/download/0.geojson?&nonce=1686752897.5874884 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f60469aaa90>: Failed to establish a new connection: [Errno 111] Connection refused'))
I'm the only user, who access this data, I wondering me why is that a problem if I try upload to the datastore.
That  happened after I started the worker.

### Expected behavior
Would be nice if its works..

**Comment by MichaelHarmsTIB** [comment]
the url works fine with firefox to get the ressource, with curl from command line from the ckan container it doesn't works.

**Comment by kowh-ai** [comment]
Support request, moving to Discussions for support

**Comment by MichaelHarmsTIB** [comment]
Hi,
I manged to create a workaround to find the problem. First why is that a support request, how will you run multiple container in a docker network, and run the xloader with datastore, if the xloader try to upload on port 80, but on that port you got an error. So I reconfigure the ckan server to port 80 and it works, but it runs without nginx, I need to configure xloader to use port 5000.
Conclusion is xloader and datastore running not with port 5000 in the same ckan container.
I would appreciate a reply how I can configure the xloader,

**Comment by MichaelHarmsTIB** [comment]
Hi,
Friday I tried with datapusher container as well, here same result, the datastore push uses localhost with port 5000 in the datapusher container.

**Comment by kowh-ai** [comment]
There is already a datapusher container running as part of the compose stack when you use [ckan-docker](https://github.com/ckan/ckan-docker) It's running on port 8800 and the datastore database are set up in the db container. Communication to datapusher is configured through env variables in the `.env` file. Replacing datapsuher with xloader would require changes but would be easier if the xloader extension (and worker) was running in the ckan container

**Comment by MichaelHarmsTIB** [comment]
I had the xloader in the ckan container and it doesn't works, reason is the port, ckan uses port 5000 and not 80, the question is in both cases, how to configure the datapusher not to use port 80.
Btw. I use your docker.dev file as template, and some versions of alpine doesn't works with ckanext-spatial, so I switched to ubuntu-focal docker image, and now running the geo plugins. Only datapusher doesn't work.
My Env:

```
DATAPUSHER_VERSION=0.0.20
CKAN_DATAPUSHER_URL=http://datapusher:8800
CKAN__DATAPUSHER__CALLBACK_URL_BASE=http://ckan:5000
DATAPUSHER_REWRITE_RESOURCES=True
DATAPUSHER_REWRITE_URL=http://ckan:5000
DATAPUSHER_MAX_CONTENT_LENGTH=10485760
DATAPUSHER_CHUNK_SIZE=16384
DATAPUSHER_CHUNK_INSERT_ROWS=250
DATAPUSHER_DOWNLOAD_TIMEOUT=30
DATAPUSHER_SSL_VERIFY=False
```
My Datapusher in docker-compose.yml
```

`  datapusher:
    container_name: ${DATAPUSHER_CONTAINER_NAME}
    image: ckan/ckan-base-datapusher:${DATAPUSHER_VERSION}
    restart: unless-stopped
    environment:
      - DATAPUSHER_MAX_CONTENT_LENGTH=${DATAPUSHER_MAX_CONTENT_LENGTH}
      - DATAPUSHER_CHUNK_SIZE=${DATAPUSHER_CHUNK_SIZE}
      - DATAPUSHER_CHUNK_INSERT_ROWS=${DATAPUSHER_CHUNK_INSERT_ROWS}
      - DATAPUSHER_DOWNLOAD_TIMEOUT=${DATAPUSHER_DOWNLOAD_TIMEOUT}
      - DATAPUSHER_SSL_VERIFY=${DATA_PUSHER_SSL_VERIFY}
      - DATAPUSHER_REWRITE_RESOURCES=${DATAPUSHER_REWRITE_RESOURCES}
      - DATAPUSHER_REWRITE_URL=${DATAPUSHER_REWRITE_URL}
    healthcheck:
      test: [ "CMD", "wget", "-qO", "/dev/null", "http://localhost:8800" ]
    networks:
      - ckan
      - web`
```
