### ISSUE TITLE
`docker-compose up` does not work

### ISSUE THREAD

**Issue by dmfenton** [ckan/ckan#3075]
The way that you are specifying environmental variables in these lines is incorrect: https://github.com/ckan/ckan/blob/master/contrib/docker/my_init.d/50_configure#L36-L49

As a result the CKAN container cannot connect to the DB or SOLR

``` bash
ckan | *** Running /etc/my_init.d/50_configure...
ckan | /etc/my_init.d/50_configure: 37: /etc/my_init.d/50_configure: DB_ENV_POSTGRES_USER: parameter not set
ckan | no DATABASE_URL specified and linked container called 'db' was not found
ckan | *** /etc/my_init.d/50_configure failed with status 1
ckan |
ckan | *** Killing all processes...
ckan exited with code 1
```

I added the ENV's for `DATABASE_URL` and `SOLR_URL` directly into docker-compose.yml and everything works.

``` yml
version: '2'
services:
  ckan:
    container_name: ckan
    image: ckan/ckan:latest
    depends_on:
      - db
      - solr
    links:
       - db
       - solr
    ports:
       - "80:80"
    environment:
       DATABASE_URL: "postgresql://ckan:ckan@db:5432/ckan"
       SOLR_URL: "http://solr:8983/solr/ckan"
  db:
    container_name: db
    image: ckan/postgresql:latest
  solr:
    container_name: solr
    image: ckan/solr:latest
```

My Docker version info:

``` bash
$ docker version                                                                                                                      [16:37:48]
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 22:37:33 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
```
