### ISSUE TITLE
Bad dataset persistence after docker-compose down

### ISSUE THREAD

**Issue by emepetres** [ckan/ckan#4425]
### CKAN Version if known (or site URL)
CKAN 2.7, using docker-compose.
The image used is compiled from 2.7 tag, with minor tweaks to resolve some bugs found. It is built by https://github.com/MSO4SC/MSOPortal/blob/master/datacatalogue/create-base-ckan-image.sh

### Please describe the expected behaviour
After docker-compose down && docker-compose up -d, datasets should be listed under `/datasets`

### Please describe the actual behaviour
After docker-compose down && docker-compose up -d, `/datasets` says "No datasets found", however, accessing to "old" dataset url still works, so the datasets are still there but they are not listed. Organizations and users are persisted correctly.

### What steps can be taken to reproduce the issue? 
1.- docker-compose up -d
2.- go to ckan and create a dataset
3.- docker-compose down && docker compose up -d
4.- go to ckan `/datasets`

This is the docker compose file I'm using:
```
version: "3.3"

services:
  ckan:
    container_name: ckan
    image: mso4sc/ckan:2.7.4
    restart: always
    links:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT}:5000"
    environment:
      # Defaults work with linked containers, change to use own Postgres, SolR, Redis
      - CKAN_SQLALCHEMY_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/ckan
      - CKAN_DATASTORE_WRITE_URL=postgresql://ckan:${POSTGRES_PASSWORD}@db/datastore
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:${DATASTORE_READONLY_PASSWORD}@db/datastore
      - CKAN_SOLR_URL=http://solr:8983/solr/ckan
      - CKAN_REDIS_URL=redis://redis:6379/1
      - CKAN_DATAPUSHER_URL=http://datapusher:8800
      - CKAN_SITE_URL=http://${CKAN_HOST}:${CKAN_PORT}
      - CKAN_MAX_UPLOAD_SIZE_MB=${CKAN_MAX_UPLOAD_SIZE_MB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - FRONTEND_ENTRYPOINT=http://${PORTAL_HOST}:${PORTAL_PORT}
      - IDM_ENTRYPOINT=${IDM_ENTRYPOINT}
      - FIWARE_ID=${IDM_CKAN_ID}
      - FIWARE_SECRET=${IDM_CKAN_SECRET}

    volumes:
      - ckan_config:/etc/ckan/default
      - ckan_home:/usr/lib/ckan/default
      - ckan_storage:/var/lib/ckan

  db:
    container_name: db
    image: ckan/postgresql
    restart: always
    environment:
      - DS_RO_PASS=${DATASTORE_READONLY_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  solr:
    container_name: solr
    image: ckan/solr
    restart: always


  redis:
    container_name: redis
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

volumes:
    ckan_config:
    ckan_home:
    ckan_storage:
    pgdata:
    redis_data:
```
