### ISSUE TITLE
Theming: User "fa-group" instead of "fa-users" for Groups

### ISSUE THREAD

**Issue by paulmueller** [ckan/ckan#5574]
**CKAN version**
2.9

**Describe the bug**
In my custom theme, I would like to change the default font-awesome icon for e.g. "Group". I can do that already for organizations and datasets by adding the following custom css:

```css
/* Override the default font-awesome icon for dataset */
.fa.fa-sitemap:before {
  content: "\f07b";
}

/* Override the default font-awesome icon for organization/circle */
.fa.fa-building-o:before {
  content: "\f17d";
}
```

However, this approach will not work with Groups, because it has the same icon as users, namely ``fa-users``.

**Expected behavior**
It would be nice, if CKAN would use ``fa-group`` instead of ``fa-users`` for all group-related icons. In font-awesome this is [actually the same icon](https://github.com/ckan/ckan/blob/2.9/ckan/public/base/vendor/font-awesome/css/font-awesome.css#L701-L704), so it would not even break anything / change anything visually. It would just be more convenient for theming.

**Additional details**
I would make a PR if you approved.
