### ISSUE TITLE
Metadata removed on update a file

### ISSUE THREAD

**Issue by guibos** [ckan/ckan#6136]
**CKAN 2.8.x**

**Describe the bug**
Currently when a file is replaced with some call like  this:
```
curl -X POST  -H "Content-Type: multipart/form-data"  -H "Authorization: xxxx"  -F "id=x" -F "upload=@test.csv" http://ckan/api/3/action/resource_update
```
All extras are removed.

**Steps to reproduce**
Create a schema like this:

```
resource_fields:
- field_name: url
  label: URL
  preset: resource_url_upload
- field_name: name
  label: Name
  form_placeholder: eg. January 2011 Gold Prices
- field_name: description
  label: Description
  form_snippet: markdown.html
  form_placeholder: Some useful notes about the data
- field_name: books
  preset: fluent_text
  label:
    en: Books
    fr: Livres
  form_languages:
    - en
    - fr
- field_name: format
  label: Format
  preset: resource_format_autocomplete
```
Create a resource with previous extra (books)

Execute:
```
curl -X POST  -H "Content-Type: multipart/form-data"  -H "Authorization: xxxx"  -F "id=x" -F "upload=@test.csv" http://ckan/api/3/action/resource_update
```

Books now is replaced by `{}`. If books was a string will be not be present in extras.,

**Expected behavior**
Not replace all extras or almost explain this situation in documentation:
[https://docs.ckan.org/en/2.8/api/index.html#uploading-a-new-version-of-a-resource-file](https://docs.ckan.org/en/2.8/api/index.html#uploading-a-new-version-of-a-resource-file)

**Additional details**
I think problem starts here:
https://github.com/ckan/ckan/blob/756776201f36653440bf4f13db2df335300d3d86/ckan/lib/dictization/model_save.py#L42

IMHO I think that best solution is  create a filestore endpoint to replace files. Currently I think is not possible to know if anyone wants to drop a extra field or only replace a file.

I want to contribute in this issue.
