### ISSUE TITLE
Setting `ckan.main_css` does not work because there is no webassets.yml file for custom files

### ISSUE THREAD

**Issue by paulmueller** [ckan/ckan#6563]
**CKAN version**
2.9.4

**Describe the bug**
I tried to set [ckan-main-css](https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-main-css), but it does not work if there is no corresponding `webassets.yml` file.

**Steps to reproduce**
Set `ckan.main_css = /base/css/my-custom.css` as described in the [docs](https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-main-css). No `my-custom.css` file is set after reloading supervisor. There is no `main.css` loaded (page does not render properly).

**Expected behavior**
The manually set my-custom.css file should replace the default main.css.

**Workaround**
Modify `/usr/lib/ckan/default/src/ckan/ckan/public/base/css/webassets.yml` and append the lines

```
my-custom:
  filters: cssrewrite
  output: base/%(version)s_my-custom.css
  contents: my-custom.css
```

**Additional Info**
I believe this is related to the recent migration to webassets from fanstatic.

**Comment by smotornyuk** [comment]
Yes, you are right, it's webassets thing. Now `ckan.main_css` is a bit broken, I would say so documentation needs to be updated.

**Comment by Gauravp-NEC** [comment]
@smotornyuk , I am interested to work on this issue. If set `ckan.main_css = /base/css/my-custom.css` then below lines should be appended in webassests.yml file?
```
my-custom:
  filters: cssrewrite
  output: base/%(version)s_my-custom.css
  contents: my-custom.css
```
The same needs to be updated in Docs: https://docs.ckan.org/en/2.9/maintaining/configuration.html#ckan-main-css? Please confirm my understanding. Thankyou :)
