### ISSUE TITLE
Dockerfile uses an old version of Ubuntu Focal

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#6635]
https://github.com/ckan/ckan/blob/86474733977828686e8fd1d1d0d3476b8cca2731/Dockerfile#L2

Shouldn't `:focal` be used instead of `:focal-20210119`? Otherwise, someone should always update this Dockerfile and run some tests to assure that compatibility is not broken, which does not seem to be the case.

**Comment by kowh-ai** [comment]
The idea of using a specific Docker base image is to minimise issues caused by a base image change update we have no control over.  eg: if we use `:focal` _or_ `:latest` an update to this from the Ubuntu team that maintains there images could cause a issue that may take a while to work out what caused the problem. An update (by the CKAN team) to a new base image can be a little more controlled

**Comment by frafra** [comment]
I can understand the reason, but that also means to have outdated images with potential security issues. Would the CKAN team consider something like depend-a-bot for Dockerfiles if someone develop some end-to-end test for that?

**Comment by EricSoroos** [comment]
For the solr one, we're pinning to solr:8 (at least in a recent pr). Ubuntu has a relatively strong promise for compatibility within a LTS distribution. In my experience/opinion, the risk from not updating for a security issue far exceeds the likelihood of a regression from the base os, especially since we are not pulling in many packages. 

(And actually going further, I'd recommend doing an apt-get dist-upgrade in the build process for the latest security updates.)

**Comment by kowh-ai** [comment]
Yes maybe `:focal` is the better option in this case (Ubuntu images). Either that or I have a monthly task of testing the latest focal image (assuming there is one), creating a PR and getting the PR merged. I'm not familiar with Dependabot @frafra but if it can help alleviate this sort of manual work I think it's a good idea!

**Comment by frafra** [comment]
@kowh-ai yes, we could create automatic PR and run tests using Dependabot.

Reference: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates

Minimal example of a possible `.github/dependabot.yml`:
```
version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
```

It could also be extended to support `pip-compile`:
```
- package-ecosystem: pip-compile
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
```
