### ISSUE TITLE
Datatables view loads extra bootstrap

### ISSUE THREAD

**Issue by EricSoroos** [ckan/ckan#7975]
## CKAN version

2.9, apparently fixed in master and 2.10

## Describe the bug

Datatables webassets includes vendor/Bootstrap-3.3.7/js/bootstrap.js, just after preloading main, which contains bootstrap 3.4.1.

```
main-js:
  output: datapreview/%(version)s_main.js
  extra:
    preload:
      - base/main
  contents:
    - vendor/Bootstrap-3.3.7/js/bootstrap.js
    - vendor/DataTables-1.10.15/js/jquery.dataTables.js
    - vendor/DataTables-1.10.15/js/dataTables.bootstrap.js
...
```

### Expected behavior

One copy of bootstrap is loaded. Since these are both part of the ckan distribution, I'd expect that the main bootstrap is used.
